/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2022-11-07 15:55:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import CNG.Db;

public final class CngPump_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");

		int id = Db.getPumpId();
		Connection con = Db.connect();
		String query = "select * from pump_registration where id = ?";
		PreparedStatement pst = con.prepareStatement(query);
		pst.setInt(1, id);
		ResultSet rs = pst.executeQuery();
		
	
      out.write('\r');
      out.write('\n');
      out.write('	');
 while(rs.next()){
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>Pump Id :</h2><p>");
      out.print( rs.getInt(1) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Pump Name :</h2><p>");
      out.print( rs.getString(2) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Address :</h2><p>");
      out.print( rs.getString(3) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>City :</h2><p>");
      out.print( rs.getString(4) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Taluka :</h2><p>");
      out.print( rs.getString(5) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>District :</h2><p>");
      out.print( rs.getString(6) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Open Time :</h2><p>");
      out.print( rs.getString(7) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Close Time :</h2><p>");
      out.print( rs.getString(8) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Mobile Number :</h2><p>");
      out.print( rs.getString(9) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Latitude :</h2><p>");
      out.print( rs.getString(10) );
      out.write("</p>\t\r\n");
      out.write("\t\t<h2>Longitude :</h2><p>");
      out.print( rs.getString(11) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>CNG in kg :</h2><p>");
      out.print( rs.getInt(12) );
      out.write("</p>\r\n");
      out.write("\t\t<h2>Status :</h2><p>");
      out.print( rs.getString(14));
      out.write("</p>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<h2><a href=\"updateCng.jsp?id=");
      out.print( rs.getInt(1));
      out.write("\">Update CNG</a></h2>\r\n");
      out.write("<h2><a href=\"pumpViewAllCng.jsp\">View All CNG pumps</a></h2>\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
